spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: 'sa'
    password: '123456'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  api:
    path: '/api/v1/employees'
  info:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
  backend:
    errors:
      EMPLOYEE_NOT_SAVE:
        description: 'Error al guardar al empleado.'
        category: INTERNAL_ERROR
      EMPLOYEE_NOT_FOUND:
        description: 'Empleado no encontrado.'
        category: NOT_FOUND
      EMPLOYEE_NOT_UPDATE:
        description: 'Error al actualizar al empleado.'
        category: INTERNAL_ERROR

server:
  port: 8081
#  servlet:
#    context-path: /api
  error:
    include-message: always

logging.level:
  com.pe.employee: DEBUG